package com.granpa.pumpselector;
import java.util.*;
public class PumpSelector {
 public static class Req{public boolean range;public double min,max;public String label,rule;}
 public static class Result{public PumpRecord r;public double head,flow,diff;public String status;public boolean estimate;}
 public static double toLPH(double v,String u){if(u==null)return v;u=u.toUpperCase(Locale.US);if(u.equals("LPM"))return v*60;if(u.equals("LPS"))return v*3600;if(u.equals("M3H"))return v*1000;return v;}
 public static Req req(boolean range,double a,double b,String unit){double x=toLPH(a,unit),y=toLPH(b,unit);if(Double.isNaN(x)||x<=0||range&&(Double.isNaN(y)||y<=0))return null;Req r=new Req();r.range=range;if(range){r.min=Math.min(x,y);r.max=Math.max(x,y);r.label="Range "+lph(r.min)+"–"+lph(r.max);r.rule="estimated flow must be inside "+lph(r.min)+"–"+lph(r.max)+" at the fixed head";}else{r.min=x;r.max=Double.NaN;r.label="Fixed flow "+lph(x);r.rule="estimated flow must be at least "+lph(x)+" at the fixed head";}return r;}
 public static ArrayList<Result> select(List<PumpRecord> rows,double head,Req req,String cat,String phase,String key){ArrayList<Result> out=new ArrayList<>();if(req==null)return out;for(PumpRecord r:rows){if(!cat(r,cat)||!phase(r.phase,phase)||!kw(r,key))continue;Double q=flowAt(r,head);if(q==null)continue;Result x=new Result();x.r=r;x.head=head;x.flow=q;x.estimate=true;if(req.range){if(q<req.min-1e-4||q>req.max+1e-4)continue;x.diff=Math.abs(q-(req.min+req.max)/2);x.status="Inside range";}else{if(q<req.min-1e-4)continue;x.diff=q-req.min;x.status=(x.diff<1?"Exact":"+"+lph(x.diff));}out.add(x);}Collections.sort(out,(a,b)->{int hp=Double.compare(a.r.hp,b.r.hp);if(hp!=0)return hp;int d=Double.compare(a.diff,b.diff);if(d!=0)return d;return a.r.model.compareToIgnoreCase(b.r.model);});return out;}
 public static ArrayList<Result> catalogue(List<PumpRecord> rows,String cat,String key){ArrayList<Result> out=new ArrayList<>();for(PumpRecord r:rows)if(cat(r,cat)&&kw(r,key)){Result x=new Result();x.r=r;out.add(x);}Collections.sort(out,(a,b)->{int hp=Double.compare(a.r.hp,b.r.hp);if(hp!=0)return hp;return a.r.model.compareToIgnoreCase(b.r.model);});return out;}
 public static Double flowAt(PumpRecord r,double head){ArrayList<double[]> pts=new ArrayList<>();for(double[] p:r.curve)if(p!=null&&p.length>=2)pts.add(new double[]{p[0],p[1]});Collections.sort(pts,Comparator.comparingDouble(a->a[0]));if(pts.size()==1)return Math.abs(pts.get(0)[0]-head)<1e-4?pts.get(0)[1]:null;for(int i=0;i<pts.size()-1;i++){double[] a=pts.get(i),b=pts.get(i+1);if(head>=Math.min(a[0],b[0])-1e-4&&head<=Math.max(a[0],b[0])+1e-4){if(Math.abs(b[0]-a[0])<1e-9)return Math.max(a[1],b[1]);return a[1]+(head-a[0])/(b[0]-a[0])*(b[1]-a[1]);}}return null;}
 public static boolean cat(PumpRecord r,String s){if(s==null||s.equals("all"))return true;String c=(r.category==null?"":r.category).toLowerCase(Locale.US);if(s.equals("borewell_all"))return c.contains("borewell");if(s.equals("monoblock_all"))return c.contains("monoblock")||c.contains("centrifugal");if(s.equals("submersible_all"))return c.contains("submersible");if(s.equals("dewatering_all"))return c.contains("dewatering")||c.contains("sewage");return s.equals(r.category);} 
 public static boolean phase(String p,String want){if(want==null||want.equals("any"))return true;p=(p==null?"":p).toUpperCase(Locale.US);if(want.equals("S"))return p.contains("S");if(want.equals("T"))return p.contains("T")||p.contains("3");return true;}
 public static boolean kw(PumpRecord r,String k){if(k==null||k.trim().isEmpty())return true;String hay=(r.model+" "+r.brand+" "+r.category+" "+r.size+" "+r.catalogueSectionText).toLowerCase(Locale.US);return hay.contains(k.toLowerCase(Locale.US))||norm(hay).contains(norm(k));}
 public static String norm(String s){return s==null?"":s.toLowerCase(Locale.US).replaceAll("[^a-z0-9]","");} public static String lph(double v){return String.format(Locale.US,"%,.0f LPH",v);} public static String head(double v){return String.format(Locale.US,"%.1f m",v);} public static String trim(double v){if(Double.isNaN(v))return"-";if(Math.abs(v-Math.round(v))<1e-5)return String.format(Locale.US,"%.0f",v);return String.format(Locale.US,"%.2f",v).replaceAll("0+$","").replaceAll("\\.$","");}
}
