package com.granpa.pumpselector;
import org.json.*;
public class PumpRecord {
 public String id="",model="",brand="",category="",phase="",hpText="",kwText="",stages="",headRangeText="",dischargeRangeText="",flowUnitOriginal="",size="",sheet="",title="",catalogueSectionText="",categoryDetail="",imageUrl="",normalizedCategory="OTHER",dataStatus="AUTO_CHECKED",dataNote="",variantLabel="",rpm="",insulationClass="",frameSize="",motorType="";
 public String catalogSegment="",catalogueYear="",sourceFile="",sourcePage="",sourceFlowUnit="",crossCheckedWith="",suctionSize="",deliverySize="",outletDN="",nrvSize="",cableSize="",freePassage="",maxSolidSize="",impellerDiameter="",ratedCurrent="",startingMethod="",minimumWellDiameter="",nominalSpeed="",rotor="",powerSupply="",cableLength="",startingCurrent="",ratedTorque="";
 public boolean selectable=true; public int page; public double hp=Double.NaN,kw=Double.NaN,minHead=Double.NaN,maxHead=Double.NaN,minFlowLPH=Double.NaN,maxFlowLPH=Double.NaN; public double[][] curve=new double[0][0];
 public static PumpRecord fromJson(JSONObject o){PumpRecord r=new PumpRecord();
  r.id=o.optString("id");r.model=o.optString("model");r.brand=o.optString("brand");r.category=o.optString("category");r.phase=o.optString("phase");r.hpText=o.optString("hpText");r.kwText=o.optString("kwText");r.stages=o.optString("stages");r.headRangeText=o.optString("headRangeText");r.dischargeRangeText=o.optString("dischargeRangeText");r.flowUnitOriginal=o.optString("flowUnitOriginal");r.size=o.optString("size");r.sheet=o.optString("sheet");r.title=o.optString("title");r.catalogueSectionText=o.optString("catalogueSectionText");r.categoryDetail=o.optString("categoryDetail");r.imageUrl=o.optString("imageUrl");r.normalizedCategory=o.optString("normalizedCategory","OTHER");r.dataStatus=o.optString("dataStatus","AUTO_CHECKED");r.dataNote=o.optString("dataNote");r.variantLabel=o.optString("variantLabel");r.rpm=o.optString("rpm");r.insulationClass=o.optString("insulationClass");r.frameSize=o.optString("frameSize");r.motorType=o.optString("motorType");
  r.catalogSegment=o.optString("catalogSegment");r.catalogueYear=o.optString("catalogueYear");r.sourceFile=o.optString("sourceFile");r.sourcePage=o.optString("sourcePage",String.valueOf(o.optInt("page")));r.sourceFlowUnit=o.optString("sourceFlowUnit",r.flowUnitOriginal);r.crossCheckedWith=o.optString("crossCheckedWith");r.suctionSize=o.optString("suctionSize");r.deliverySize=o.optString("deliverySize");r.outletDN=o.optString("outletDN");r.nrvSize=o.optString("nrvSize");r.cableSize=o.optString("cableSize");r.freePassage=o.optString("freePassage");r.maxSolidSize=o.optString("maxSolidSize");r.impellerDiameter=o.optString("impellerDiameter");r.ratedCurrent=o.optString("ratedCurrent");r.startingMethod=o.optString("startingMethod");r.minimumWellDiameter=o.optString("minimumWellDiameter");r.nominalSpeed=o.optString("nominalSpeed");r.rotor=o.optString("rotor");r.powerSupply=o.optString("powerSupply");r.cableLength=o.optString("cableLength");r.startingCurrent=o.optString("startingCurrent");r.ratedTorque=o.optString("ratedTorque");
  r.selectable=o.optBoolean("selectable",true);r.page=o.optInt("page");r.hp=o.optDouble("hp",Double.NaN);r.kw=o.optDouble("kw",Double.NaN);r.minHead=o.optDouble("minHead",Double.NaN);r.maxHead=o.optDouble("maxHead",Double.NaN);r.minFlowLPH=o.optDouble("minFlowLPH",Double.NaN);r.maxFlowLPH=o.optDouble("maxFlowLPH",Double.NaN);JSONArray a=o.optJSONArray("curve");if(a!=null){r.curve=new double[a.length()][2];for(int i=0;i<a.length();i++){JSONArray p=a.optJSONArray(i);if(p!=null){r.curve[i][0]=p.optDouble(0);r.curve[i][1]=p.optDouble(1);}}}return r;}
 public boolean isMotor(){return "MOTOR".equalsIgnoreCase(normalizedCategory);}
}
