package com.granpa.pumpselector;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;
public class PumpDetailsActivity extends Activity{PumpRecord rec;boolean has;double head,flow;
 protected void onCreate(Bundle b){super.onCreate(b);rec=PumpRepository.findById(this,getIntent().getStringExtra("id"));has=getIntent().getBooleanExtra("estimate",false);head=getIntent().getDoubleExtra("head",Double.NaN);flow=getIntent().getDoubleExtra("flow",Double.NaN);LinearLayout root=Ui.root(this);if(rec==null){root.addView(Ui.text(this,"Model not found",22,Ui.TEXT,1));setContentView(root);return;}root.addView(header());root.addView(chartCard());root.addView(detailCard("Curve points used",curveRows()));root.addView(detailCard("Quick specs",quickRows()));root.addView(catalogueCard());root.addView(actions());setContentView(Ui.scroll(this,root));}
 LinearLayout header(){LinearLayout top=Ui.card(this);LinearLayout row=Ui.row(this);ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.app_logo);row.addView(logo,new LinearLayout.LayoutParams(Ui.dp(this,42),Ui.dp(this,42)));TextView model=Ui.text(this,rec.model,30,Ui.TEXT,1);model.setPadding(Ui.dp(this,10),0,0,0);row.addView(model);top.addView(row);top.addView(Ui.text(this,rec.category,16,Ui.BLUE,1));top.addView(Ui.text(this,PumpSelector.trim(rec.hp)+" HP  •  "+PumpSelector.trim(rec.kw)+" kW  •  "+phaseLabel(rec.phase),16,Ui.MUTED,1));if(has&&!Double.isNaN(head)&&!Double.isNaN(flow))top.addView(Ui.text(this,"Estimated at selected head: "+PumpSelector.lph(flow)+" at "+PumpSelector.head(head),17,Ui.GREEN,1));return top;}
 LinearLayout chartCard(){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,"Performance curve",20,Ui.TEXT,1));TextView n=Ui.text(this,"One complete end-to-end curve line. Orange point is the selected operating point.",13,Ui.MUTED,0);Ui.mb(this,n,8);c.addView(n);PerformanceCurveView chart=new PerformanceCurveView(this);chart.setData(rec.curve,has?head:null,has?flow:null);c.addView(chart,new LinearLayout.LayoutParams(-1,Ui.dp(this,330)));return c;}
 LinearLayout catalogueCard(){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,"Catalogue section",18,Ui.TEXT,1));TextView t=Ui.text(this,catalogueText(),14,Ui.MUTED,0);t.setLineSpacing(Ui.dp(this,2),1f);t.setTextIsSelectable(true);c.addView(t);return c;}
 LinearLayout actions(){LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);LinearLayout row=Ui.row(this);Button wa=Ui.primary(this,"Share WhatsApp");row.addView(wa,new LinearLayout.LayoutParams(0,-2,1));Button dl=Ui.blue(this,"Download Image");LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(0,-2,1);dp.setMargins(Ui.dp(this,10),0,0,0);row.addView(dl,dp);Ui.mb(this,row,10);outer.addView(row);LinearLayout row2=Ui.row(this);Button copy=Ui.secondary(this,"Copy model number");row2.addView(copy,new LinearLayout.LayoutParams(0,-2,1));Button back=Ui.secondary(this,"Back");LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,-2,1);bp.setMargins(Ui.dp(this,10),0,0,0);row2.addView(back,bp);outer.addView(row2);wa.setOnClickListener(v->ShareImageBuilder.shareWhatsApp(this,rec,has,head,flow));dl.setOnClickListener(v->ShareImageBuilder.download(this,rec,has,head,flow));copy.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("model",rec.model));Toast.makeText(this,"Model copied",Toast.LENGTH_SHORT).show();});back.setOnClickListener(v->finish());return outer;}
 String[][] curveRows(){ArrayList<String[]> rows=new ArrayList<>();double[][] pts=rec.curve;int maxFlow=-1,maxHead=-1;double bestF=-1,bestH=-1;if(pts!=null){for(int i=0;i<pts.length;i++)if(pts[i]!=null&&pts[i].length>=2){if(pts[i][1]>bestF){bestF=pts[i][1];maxFlow=i;}if(pts[i][0]>bestH){bestH=pts[i][0];maxHead=i;}}for(int i=0;i<pts.length;i++)if(pts[i]!=null&&pts[i].length>=2){String label=i==maxFlow?"Max Flow":i==maxHead?"Max Head":"BEP";rows.add(new String[]{label,String.format(Locale.US,"%,.0f LPH at %.1f m",pts[i][1],pts[i][0])});}}if(has&&!Double.isNaN(head)&&!Double.isNaN(flow))rows.add(new String[]{"Selected point",String.format(Locale.US,"%,.0f LPH at %.1f m",flow,head)});return rows.toArray(new String[0][]);}String[][] quickRows(){return new String[][]{{"Delivery / Pipe size",empty(rec.size)?"-":rec.size},{"Page",String.valueOf(rec.page)},{"Head range",safe(rec.headRangeText)+" m"},{"Discharge range",safe(rec.dischargeRangeText)+" "+safe(rec.flowUnitOriginal)},{"Flow range",flowRange(rec)},{"Brand",empty(rec.brand)?"-":rec.brand},{"Stages",empty(rec.stages)?"-":rec.stages},{"Sheet",empty(rec.sheet)?"Page "+rec.page+" Layout":rec.sheet}};}
 LinearLayout detailCard(String title,String[][] rows){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,title,18,Ui.TEXT,1));for(String[] row:rows){LinearLayout line=Ui.row(this);line.setPadding(0,Ui.dp(this,6),0,Ui.dp(this,6));TextView l=Ui.text(this,row[0],15,Ui.MUTED,1);TextView r=Ui.text(this,row[1],16,Ui.TEXT,0);line.addView(l,new LinearLayout.LayoutParams(0,-2,1));line.addView(r,new LinearLayout.LayoutParams(0,-2,1));c.addView(line);}return c;}String catalogueText(){String s=safe(rec.catalogueSectionText);if(!s.isEmpty())return s;if(!empty(rec.title))return rec.title;if(!empty(rec.brand)&&!empty(rec.category))return rec.brand+" | "+rec.category;return rec.category;}String phaseLabel(String p){p=safe(p).toUpperCase(Locale.US);if(p.contains("S"))return"Single Phase";if(p.contains("T"))return"Three Phase";return p.isEmpty()?"Phase -":p;}String flowRange(PumpRecord r){return Double.isNaN(r.minFlowLPH)||Double.isNaN(r.maxFlowLPH)?"-":PumpSelector.lph(r.minFlowLPH).replace(" LPH","")+" – "+PumpSelector.lph(r.maxFlowLPH);}String safe(String s){return s==null?"":s.trim();}boolean empty(String s){return safe(s).isEmpty();}
}
