package com.granpa.pumpselector;

import android.app.Activity;
import android.content.Intent;
import android.graphics.*;
import android.net.Uri;
import android.widget.Toast;
import androidx.core.content.FileProvider;
import java.io.File;
import java.io.FileOutputStream;
import java.util.*;

public class ShareImageBuilder {
    public static Bitmap build(Activity a, PumpRecord r, boolean hasEstimate, double head, double flow) {
        int w = 1080, h = 1350;
        Bitmap bm = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(bm);
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        c.drawColor(Color.rgb(246, 248, 251));

        p.setColor(Color.WHITE);
        RectF card = new RectF(30, 30, w - 30, h - 30);
        c.drawRoundRect(card, 32, 32, p);

        Bitmap logo = BitmapFactory.decodeResource(a.getResources(), R.drawable.app_logo);
        if (logo != null) c.drawBitmap(logo, null, new RectF(70, 70, 150, 150), null);

        Paint text = new Paint(Paint.ANTI_ALIAS_FLAG);
        text.setColor(Color.rgb(16,32,51));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(56);
        c.drawText("Granpa", 170, 125, text);

        text.setTextSize(52);
        c.drawText("Recommended Pump", 70, 235, text);

        text.setColor(Color.rgb(0,83,176));
        text.setTextSize(70);
        c.drawText(safe(r.model), 70, 330, text);

        int y = 395;
        drawChip(c, "⚡", PumpSelector.trim(r.hp) + " HP", 70, y, 210, 120);
        drawChip(c, "⚡", PumpSelector.trim(r.kw) + " kW", 300, y, 210, 120);
        drawChip(c, "~", phaseLabel(r.phase), 530, y, 230, 120);
        drawChip(c, "⛽", safe(r.category).replace(" ", "\n"), 780, y, 230, 120);

        y = 550;
        p.setColor(Color.rgb(247, 251, 255));
        p.setStyle(Paint.Style.FILL);
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(207, 221, 236));
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);
        text.setColor(Color.rgb(16,32,51));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(30);
        String req = hasEstimate ? "Suitable for " + PumpSelector.head(head) + " head  •  Estimated " + PumpSelector.lph(flow) : "Model details and performance curve";
        c.drawText(req, 115, y + 45, text);

        y = 650;
        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(255,248,238));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(255,132,0));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);
        text.setColor(Color.rgb(16,32,51));
        text.setTextSize(33);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText(hasEstimate ? "Estimated at " + PumpSelector.head(head) + ":" : "Flow range:", 125, y + 58, text);
        text.setColor(Color.rgb(232,92,0));
        text.setTextSize(48);
        String out = hasEstimate ? PumpSelector.lph(flow) : flowRange(r);
        c.drawText(out, 610, y + 60, text);

        drawChart(c, r, hasEstimate, head, flow, new RectF(90, 790, 990, 1190));

        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(247, 251, 255));
        c.drawRoundRect(new RectF(70, 1235, 1010, 1300), 18, 18, p);
        if (logo != null) c.drawBitmap(logo, null, new RectF(95, 1245, 145, 1295), null);
        text.setColor(Color.rgb(96,112,133));
        text.setTextSize(24);
        c.drawText("Generated by", 165, 1278, text);
        text.setColor(Color.rgb(0,83,176));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText("Granpa Pump Selector", 300, 1278, text);
        return bm;
    }

    public static File save(Activity a, Bitmap bm) throws Exception {
        File dir = new File(a.getCacheDir(), "share");
        if (!dir.exists()) dir.mkdirs();
        File file = new File(dir, "granpa_pump_share.png");
        FileOutputStream out = new FileOutputStream(file);
        bm.compress(Bitmap.CompressFormat.PNG, 100, out);
        out.flush();
        out.close();
        return file;
    }

    public static void shareImage(Activity a, PumpRecord r, boolean hasEstimate, double head, double flow, boolean whatsappOnly) {
        try {
            Bitmap bm = build(a, r, hasEstimate, head, flow);
            File file = save(a, bm);
            Uri uri = FileProvider.getUriForFile(a, a.getPackageName() + ".fileprovider", file);
            Intent i = new Intent(Intent.ACTION_SEND);
            i.setType("image/png");
            i.putExtra(Intent.EXTRA_STREAM, uri);
            i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            if (whatsappOnly) {
                i.setPackage("com.whatsapp");
                try { a.startActivity(i); return; }
                catch (Exception ignored) {
                    i.setPackage("com.whatsapp.w4b");
                    try { a.startActivity(i); return; }
                    catch (Exception ignored2) {}
                }
                Toast.makeText(a, "WhatsApp not found. Opening share menu.", Toast.LENGTH_SHORT).show();
                i.setPackage(null);
            }
            a.startActivity(Intent.createChooser(i, "Share pump image"));
        } catch (Exception e) {
            Toast.makeText(a, "Unable to create share image", Toast.LENGTH_LONG).show();
        }
    }

    static void drawChip(Canvas c, String icon, String label, int x, int y, int w, int h) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setColor(Color.WHITE);
        c.drawRoundRect(new RectF(x,y,x+w,y+h),18,18,p);
        p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(2); p.setColor(Color.rgb(207,221,236));
        c.drawRoundRect(new RectF(x,y,x+w,y+h),18,18,p);
        Paint t = new Paint(Paint.ANTI_ALIAS_FLAG);
        t.setColor(Color.rgb(0,83,176)); t.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD)); t.setTextSize(34); t.setTextAlign(Paint.Align.CENTER);
        c.drawText(icon, x+w/2f, y+42, t);
        t.setColor(Color.rgb(16,32,51)); t.setTextSize(26);
        String[] lines = label.split("\n");
        for(int i=0;i<lines.length;i++) c.drawText(lines[i], x+w/2f, y+78+i*28, t);
    }

    static void drawChart(Canvas c, PumpRecord r, boolean hasEstimate, double head, double flow, RectF outer) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setStyle(Paint.Style.FILL); p.setColor(Color.WHITE);
        c.drawRoundRect(outer, 20, 20, p);
        p.setStyle(Paint.Style.STROKE); p.setStrokeWidth(2); p.setColor(Color.rgb(221,229,239));
        c.drawRoundRect(outer, 20, 20, p);

        RectF plot = new RectF(outer.left+80, outer.top+55, outer.right-35, outer.bottom-90);
        ArrayList<double[]> pts = new ArrayList<>();
        if(r.curve!=null) for(double[] q:r.curve) if(q!=null&&q.length>=2) pts.add(new double[]{q[0],q[1]});
        Collections.sort(pts, Comparator.comparingDouble(a -> a[1]));
        if(pts.isEmpty()) return;
        double minF=pts.get(0)[1], maxF=pts.get(pts.size()-1)[1], maxH=0;
        for(double[] q:pts){minF=Math.min(minF,q[1]);maxF=Math.max(maxF,q[1]);maxH=Math.max(maxH,q[0]);}
        if(hasEstimate){minF=Math.min(minF,flow);maxF=Math.max(maxF,flow);maxH=Math.max(maxH,head);}
        if(maxF-minF<1) maxF=minF+1000;
        maxH=Math.ceil(maxH*1.15/10.0)*10.0;

        Paint grid=new Paint(Paint.ANTI_ALIAS_FLAG);grid.setColor(Color.rgb(225,232,241));grid.setStrokeWidth(1.5f);
        Paint text=new Paint(Paint.ANTI_ALIAS_FLAG);text.setColor(Color.rgb(16,32,51));text.setTextSize(22);text.setTextAlign(Paint.Align.CENTER);
        for(int i=0;i<=5;i++){float x=plot.left+i*plot.width()/5f;c.drawLine(x,plot.top,x,plot.bottom,grid);c.drawText(String.format(Locale.US,"%,.0f",minF+(maxF-minF)*i/5),x,outer.bottom-45,text);}
        text.setTextAlign(Paint.Align.RIGHT);
        for(int i=0;i<=5;i++){float y=plot.bottom-i*plot.height()/5f;c.drawLine(plot.left,y,plot.right,y,grid);c.drawText(String.format(Locale.US,"%.0f",maxH*i/5),plot.left-14,y+8,text);}
        Paint axis=new Paint(Paint.ANTI_ALIAS_FLAG);axis.setColor(Color.rgb(96,112,133));axis.setStrokeWidth(2);
        c.drawLine(plot.left,plot.top,plot.left,plot.bottom,axis);c.drawLine(plot.left,plot.bottom,plot.right,plot.bottom,axis);
        text.setTextAlign(Paint.Align.CENTER); text.setTextSize(26); c.drawText("Flow Rate (LPH)", plot.centerX(), outer.bottom-10, text);
        c.save(); c.rotate(-90, outer.left+35, plot.centerY()); c.drawText("Head (m)", outer.left+35, plot.centerY(), text); c.restore();

        Paint curvePaint=new Paint(Paint.ANTI_ALIAS_FLAG);curvePaint.setColor(Color.rgb(0,96,216));curvePaint.setStyle(Paint.Style.STROKE);curvePaint.setStrokeWidth(5);
        Path path=new Path();
        for(int i=0;i<pts.size();i++){
            float x=x(pts.get(i)[1],minF,maxF,plot), y=y(pts.get(i)[0],maxH,plot);
            if(i==0)path.moveTo(x,y);
            else {float px=x(pts.get(i-1)[1],minF,maxF,plot), py=y(pts.get(i-1)[0],maxH,plot);float mx=(px+x)/2f;path.cubicTo(mx,py,mx,y,x,y);}
        }
        c.drawPath(path,curvePaint);
        if(hasEstimate){
            float sx=x(flow,minF,maxF,plot), sy=y(head,maxH,plot);
            Paint dash=new Paint(Paint.ANTI_ALIAS_FLAG);dash.setColor(Color.rgb(255,132,0));dash.setStyle(Paint.Style.STROKE);dash.setStrokeWidth(2);dash.setPathEffect(new DashPathEffect(new float[]{10,8},0));
            c.drawLine(plot.left,sy,sx,sy,dash);c.drawLine(sx,sy,sx,plot.bottom,dash);
            Paint dot=new Paint(Paint.ANTI_ALIAS_FLAG);dot.setColor(Color.rgb(255,132,0));c.drawCircle(sx,sy,12,dot);
        }
        text.setColor(Color.rgb(16,32,51)); text.setTextAlign(Paint.Align.LEFT); text.setTextSize(24);
        c.drawText(r.model+" Performance Curve", outer.left+130, outer.bottom-28, text);
    }

    static float x(double f,double minF,double maxF,RectF r){return (float)(r.left+(f-minF)/(maxF-minF)*r.width());}
    static float y(double h,double maxH,RectF r){return (float)(r.bottom-(h/maxH)*r.height());}
    static String safe(String s){return s==null?"":s.trim();}
    static String phaseLabel(String p){p=safe(p).toUpperCase(Locale.US); if(p.contains("S"))return "Single Phase"; if(p.contains("T"))return "Three Phase"; return p.isEmpty()?"Phase -":p;}
    static String flowRange(PumpRecord r){return Double.isNaN(r.minFlowLPH)||Double.isNaN(r.maxFlowLPH)?"-":PumpSelector.lph(r.minFlowLPH).replace(" LPH","")+"–"+PumpSelector.lph(r.maxFlowLPH);}
}
