package com.granpa.pumpselector;

import android.app.Activity;
import android.content.ContentResolver;
import android.content.ContentValues;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.DashPathEffect;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.RectF;
import android.graphics.Typeface;
import android.net.Uri;
import android.os.Build;
import android.os.Environment;
import android.provider.MediaStore;
import android.widget.Toast;

import androidx.core.content.FileProvider;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Locale;

public class ShareImageBuilder {
    public static Bitmap build(Activity activity, PumpRecord r, boolean hasEstimate, double head, double flow) {
        int w = 1080;
        int h = 1500;
        Bitmap bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(bitmap);
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        c.drawColor(Color.rgb(246, 248, 251));

        p.setColor(Color.WHITE);
        p.setStyle(Paint.Style.FILL);
        RectF card = new RectF(30, 30, w - 30, h - 30);
        c.drawRoundRect(card, 32, 32, p);

        Bitmap logo = BitmapFactory.decodeResource(activity.getResources(), R.drawable.app_logo);
        if (logo != null) c.drawBitmap(logo, null, new RectF(70, 70, 150, 150), null);

        Paint text = new Paint(Paint.ANTI_ALIAS_FLAG);
        text.setColor(Ui.TEXT);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(56);
        c.drawText("Granpa", 170, 125, text);

        text.setTextSize(52);
        c.drawText("Recommended Pump", 70, 235, text);

        text.setColor(Color.rgb(0, 83, 176));
        text.setTextSize(70);
        drawSingleLineFit(c, safe(r.model), 70, 330, text, 900);

        int y = 395;
        drawChip(c, "HP", PumpSelector.trim(r.hp) + " HP", 70, y, 210, 120);
        drawChip(c, "kW", PumpSelector.trim(r.kw) + " kW", 300, y, 210, 120);
        drawChip(c, "~", phaseLabel(r.phase), 530, y, 230, 120);
        drawChip(c, "Type", compactType(r.category), 780, y, 230, 120);

        y = 550;
        p.setColor(Color.rgb(247, 251, 255));
        p.setStyle(Paint.Style.FILL);
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(207, 221, 236));
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);

        text.setColor(Ui.TEXT);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(30);
        String req = hasEstimate
                ? "Suitable for " + PumpSelector.head(head) + " head  •  Estimated " + PumpSelector.lph(flow)
                : "Model details and complete performance curve";
        drawSingleLineFit(c, req, 115, y + 45, text, 860);

        y = 650;
        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(255, 248, 238));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(255, 132, 0));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);

        text.setColor(Ui.TEXT);
        text.setTextSize(33);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText(hasEstimate ? "Estimated at " + PumpSelector.head(head) + ":" : "Flow range:", 125, y + 58, text);

        text.setColor(Color.rgb(232, 92, 0));
        text.setTextSize(48);
        text.setTextAlign(Paint.Align.RIGHT);
        String out = hasEstimate ? PumpSelector.lph(flow) : flowRange(r);
        c.drawText(out, 960, y + 60, text);
        text.setTextAlign(Paint.Align.LEFT);

        drawChart(c, r, hasEstimate, head, flow, new RectF(70, 790, 1010, 1320));

        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(247, 251, 255));
        c.drawRoundRect(new RectF(70, 1380, 1010, 1445), 18, 18, p);
        if (logo != null) c.drawBitmap(logo, null, new RectF(95, 1390, 145, 1440), null);

        text.setColor(Ui.MUTED);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        text.setTextSize(24);
        String left = "Generated by ";
        c.drawText(left, 165, 1423, text);
        float nextX = 165 + text.measureText(left);
        text.setColor(Color.rgb(0, 83, 176));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText("Granpa Pump Selector", nextX, 1423, text);

        return bitmap;
    }

    public static void shareWhatsApp(Activity activity, PumpRecord r, boolean hasEstimate, double head, double flow) {
        try {
            Bitmap bitmap = build(activity, r, hasEstimate, head, flow);
            File file = saveToCache(activity, bitmap);
            Uri uri = FileProvider.getUriForFile(activity, activity.getPackageName() + ".fileprovider", file);

            Intent intent = new Intent(Intent.ACTION_SEND);
            intent.setType("image/png");
            intent.putExtra(Intent.EXTRA_STREAM, uri);
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);

            intent.setPackage("com.whatsapp");
            try {
                activity.startActivity(intent);
                return;
            } catch (Exception ignored) {}

            intent.setPackage("com.whatsapp.w4b");
            try {
                activity.startActivity(intent);
                return;
            } catch (Exception ignored) {}

            Toast.makeText(activity, "WhatsApp not found", Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            Toast.makeText(activity, "Unable to create WhatsApp image", Toast.LENGTH_LONG).show();
        }
    }

    public static void downloadImage(Activity activity, PumpRecord r, boolean hasEstimate, double head, double flow) {
        try {
            Bitmap bitmap = build(activity, r, hasEstimate, head, flow);
            String name = "Granpa_" + safe(r.model).replaceAll("[^a-zA-Z0-9_-]", "_") + ".png";
            Uri saved = saveToPictures(activity, bitmap, name);
            if (saved != null) {
                Toast.makeText(activity, "Image saved to Pictures / Granpa", Toast.LENGTH_LONG).show();
            } else {
                Toast.makeText(activity, "Image saved", Toast.LENGTH_LONG).show();
            }
        } catch (Exception e) {
            Toast.makeText(activity, "Unable to download image", Toast.LENGTH_LONG).show();
        }
    }

    private static File saveToCache(Activity activity, Bitmap bitmap) throws Exception {
        File dir = new File(activity.getCacheDir(), "share");
        if (!dir.exists()) dir.mkdirs();
        File file = new File(dir, "granpa_pump_share.png");
        FileOutputStream output = new FileOutputStream(file);
        bitmap.compress(Bitmap.CompressFormat.PNG, 100, output);
        output.flush();
        output.close();
        return file;
    }

    private static Uri saveToPictures(Activity activity, Bitmap bitmap, String fileName) throws Exception {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            ContentResolver resolver = activity.getContentResolver();
            ContentValues values = new ContentValues();
            values.put(MediaStore.Images.Media.DISPLAY_NAME, fileName);
            values.put(MediaStore.Images.Media.MIME_TYPE, "image/png");
            values.put(MediaStore.Images.Media.RELATIVE_PATH, Environment.DIRECTORY_PICTURES + "/Granpa");
            values.put(MediaStore.Images.Media.IS_PENDING, 1);

            Uri uri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values);
            if (uri == null) return null;

            OutputStream output = resolver.openOutputStream(uri);
            if (output != null) {
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, output);
                output.flush();
                output.close();
            }

            values.clear();
            values.put(MediaStore.Images.Media.IS_PENDING, 0);
            resolver.update(uri, values, null, null);
            return uri;
        } else {
            File dir = activity.getExternalFilesDir(Environment.DIRECTORY_PICTURES);
            if (dir == null) dir = activity.getFilesDir();
            File granpa = new File(dir, "Granpa");
            if (!granpa.exists()) granpa.mkdirs();
            File file = new File(granpa, fileName);
            FileOutputStream output = new FileOutputStream(file);
            bitmap.compress(Bitmap.CompressFormat.PNG, 100, output);
            output.flush();
            output.close();
            return Uri.fromFile(file);
        }
    }

    private static void drawChip(Canvas c, String title, String label, int x, int y, int w, int h) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setColor(Color.WHITE);
        p.setStyle(Paint.Style.FILL);
        c.drawRoundRect(new RectF(x, y, x + w, y + h), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(207, 221, 236));
        c.drawRoundRect(new RectF(x, y, x + w, y + h), 18, 18, p);

        Paint t = new Paint(Paint.ANTI_ALIAS_FLAG);
        t.setColor(Color.rgb(0, 83, 176));
        t.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        t.setTextSize(27);
        t.setTextAlign(Paint.Align.CENTER);
        c.drawText(title, x + w / 2f, y + 40, t);

        t.setColor(Ui.TEXT);
        t.setTextSize(label.contains("\n") ? 24 : 26);
        String[] lines = label.split("\n");
        float startY = lines.length == 1 ? y + 82 : y + 72;
        for (int i = 0; i < lines.length && i < 2; i++) {
            c.drawText(lines[i], x + w / 2f, startY + i * 28, t);
        }
    }

    private static void drawChart(Canvas c, PumpRecord r, boolean hasEstimate, double head, double flow, RectF outer) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.WHITE);
        c.drawRoundRect(outer, 20, 20, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(221, 229, 239));
        c.drawRoundRect(outer, 20, 20, p);

        Paint title = new Paint(Paint.ANTI_ALIAS_FLAG);
        title.setColor(Ui.TEXT);
        title.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        title.setTextSize(30);
        c.drawText("Performance Curve", outer.left + 32, outer.top + 42, title);

        RectF plot = new RectF(outer.left + 95, outer.top + 82, outer.right - 35, outer.bottom - 160);
        ArrayList<double[]> real = new ArrayList<>();
        if (r.curve != null) {
            for (double[] q : r.curve) {
                if (q != null && q.length >= 2 && !Double.isNaN(q[0]) && !Double.isNaN(q[1])) {
                    real.add(new double[]{q[0], q[1]});
                }
            }
        }
        Collections.sort(real, Comparator.comparingDouble(a -> a[1]));
        if (real.isEmpty()) return;

        double maxFlow = 0;
        double maxHead = 0;
        for (double[] q : real) {
            maxFlow = Math.max(maxFlow, q[1]);
            maxHead = Math.max(maxHead, q[0]);
        }
        if (hasEstimate) {
            maxFlow = Math.max(maxFlow, flow);
            maxHead = Math.max(maxHead, head);
        }
        double axisFlow = roundUp(maxFlow, niceFlowStep(maxFlow));
        double axisHead = roundUp(Math.max(10, maxHead * 1.08), 10);

        Paint grid = new Paint(Paint.ANTI_ALIAS_FLAG);
        grid.setColor(Color.rgb(225, 232, 241));
        grid.setStrokeWidth(1.5f);
        Paint axis = new Paint(Paint.ANTI_ALIAS_FLAG);
        axis.setColor(Ui.MUTED);
        axis.setStrokeWidth(2);
        Paint text = new Paint(Paint.ANTI_ALIAS_FLAG);
        text.setColor(Ui.TEXT);
        text.setTextSize(22);
        text.setTextAlign(Paint.Align.CENTER);

        for (int i = 0; i <= 5; i++) {
            float gx = plot.left + i * plot.width() / 5f;
            c.drawLine(gx, plot.top, gx, plot.bottom, grid);
            c.drawText(String.format(Locale.US, "%,.0f", axisFlow * i / 5), gx, plot.bottom + 34, text);
        }
        text.setTextAlign(Paint.Align.RIGHT);
        for (int i = 0; i <= 5; i++) {
            float gy = plot.bottom - i * plot.height() / 5f;
            c.drawLine(plot.left, gy, plot.right, gy, grid);
            c.drawText(String.format(Locale.US, "%.0f", axisHead * i / 5), plot.left - 14, gy + 8, text);
        }
        c.drawLine(plot.left, plot.top, plot.left, plot.bottom, axis);
        c.drawLine(plot.left, plot.bottom, plot.right, plot.bottom, axis);

        text.setTextAlign(Paint.Align.CENTER);
        text.setTextSize(26);
        c.drawText("Flow Rate (LPH)", plot.centerX(), plot.bottom + 74, text);
        c.save();
        c.rotate(-90, outer.left + 42, plot.centerY());
        c.drawText("Head (m)", outer.left + 42, plot.centerY(), text);
        c.restore();

        ArrayList<double[]> display = new ArrayList<>();
        display.add(new double[]{maxHead, 0});
        display.addAll(real);
        display.add(new double[]{0, axisFlow});

        Paint curvePaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        curvePaint.setColor(Color.rgb(0, 96, 216));
        curvePaint.setStyle(Paint.Style.STROKE);
        curvePaint.setStrokeWidth(5);
        curvePaint.setStrokeCap(Paint.Cap.ROUND);
        curvePaint.setStrokeJoin(Paint.Join.ROUND);

        Path path = new Path();
        for (int i = 0; i < display.size(); i++) {
            float cx = x(display.get(i)[1], axisFlow, plot);
            float cy = y(display.get(i)[0], axisHead, plot);
            if (i == 0) path.moveTo(cx, cy);
            else {
                float px = x(display.get(i - 1)[1], axisFlow, plot);
                float py = y(display.get(i - 1)[0], axisHead, plot);
                float mx = (px + cx) / 2f;
                path.cubicTo(mx, py, mx, cy, cx, cy);
            }
        }
        c.drawPath(path, curvePaint);

        if (hasEstimate) {
            float sx = x(flow, axisFlow, plot);
            float sy = y(head, axisHead, plot);
            Paint dash = new Paint(Paint.ANTI_ALIAS_FLAG);
            dash.setColor(Color.rgb(255, 132, 0));
            dash.setStyle(Paint.Style.STROKE);
            dash.setStrokeWidth(2);
            dash.setPathEffect(new DashPathEffect(new float[]{10, 8}, 0));
            c.drawLine(plot.left, sy, sx, sy, dash);
            c.drawLine(sx, sy, sx, plot.bottom, dash);
            Paint dot = new Paint(Paint.ANTI_ALIAS_FLAG);
            dot.setColor(Color.rgb(255, 132, 0));
            c.drawCircle(sx, sy, 13, dot);
        }

        Paint legend = new Paint(Paint.ANTI_ALIAS_FLAG);
        legend.setTextSize(24);
        legend.setColor(Ui.TEXT);
        legend.setTextAlign(Paint.Align.LEFT);
        Paint blueLine = new Paint(Paint.ANTI_ALIAS_FLAG);
        blueLine.setColor(Color.rgb(0, 96, 216));
        blueLine.setStrokeWidth(5);
        blueLine.setStrokeCap(Paint.Cap.ROUND);
        float ly = outer.bottom - 38;
        c.drawLine(outer.left + 100, ly - 7, outer.left + 150, ly - 7, blueLine);
        drawSingleLineFit(c, r.model + " Performance Curve", outer.left + 165, ly, legend, 380);
        Paint orange = new Paint(Paint.ANTI_ALIAS_FLAG);
        orange.setColor(Color.rgb(255, 132, 0));
        c.drawCircle(outer.left + 615, ly - 7, 10, orange);
        c.drawText("Selected Point", outer.left + 635, ly, legend);
    }

    private static void drawSingleLineFit(Canvas c, String s, float x, float y, Paint paint, float maxWidth) {
        float oldSize = paint.getTextSize();
        while (paint.measureText(s) > maxWidth && paint.getTextSize() > 18) {
            paint.setTextSize(paint.getTextSize() - 1);
        }
        c.drawText(s, x, y, paint);
        paint.setTextSize(oldSize);
    }

    private static double niceFlowStep(double maxFlow) {
        if (maxFlow <= 1000) return 200;
        if (maxFlow <= 3000) return 500;
        if (maxFlow <= 10000) return 1000;
        if (maxFlow <= 30000) return 5000;
        return 10000;
    }

    private static double roundUp(double value, double step) {
        return Math.ceil(value / step) * step;
    }

    private static float x(double flow, double axisFlow, RectF plot) {
        return (float) (plot.left + (flow / axisFlow) * plot.width());
    }

    private static float y(double head, double axisHead, RectF plot) {
        return (float) (plot.bottom - (head / axisHead) * plot.height());
    }

    private static String safe(String s) { return s == null ? "" : s.trim(); }

    private static String phaseLabel(String p) {
        p = safe(p).toUpperCase(Locale.US);
        if (p.contains("S")) return "Single Phase";
        if (p.contains("T")) return "Three Phase";
        return p.isEmpty() ? "Phase -" : p;
    }

    private static String compactType(String category) {
        String c = safe(category).toLowerCase(Locale.US);
        if (c.contains("borewell")) return "Borewell\nSubmersible";
        if (c.contains("openwell")) return "Openwell\nSubmersible";
        if (c.contains("monoblock")) return "Monoblock";
        if (c.contains("centrifugal")) return "Centrifugal";
        return safe(category).replace(" - ", "\n");
    }

    private static String flowRange(PumpRecord r) {
        if (Double.isNaN(r.minFlowLPH) || Double.isNaN(r.maxFlowLPH)) return "-";
        return PumpSelector.lph(r.minFlowLPH).replace(" LPH", "") + "–" + PumpSelector.lph(r.maxFlowLPH);
    }
}
