package com.granpa.pumpselector;

import android.app.Activity;
import android.content.Intent;
import android.graphics.*;
import android.net.Uri;
import android.widget.Toast;
import androidx.core.content.FileProvider;
import java.io.File;
import java.io.FileOutputStream;
import java.util.*;

public class ShareImageBuilder {
    public static Bitmap build(Activity a, PumpRecord r, boolean hasEstimate, double head, double flow) {
        int w = 1080, h = 1500;
        Bitmap bm = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(bm);
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        c.drawColor(Color.rgb(246, 248, 251));

        p.setColor(Color.WHITE);
        p.setStyle(Paint.Style.FILL);
        RectF card = new RectF(30, 30, w - 30, h - 30);
        c.drawRoundRect(card, 32, 32, p);

        Bitmap logo = BitmapFactory.decodeResource(a.getResources(), R.drawable.app_logo);
        if (logo != null) c.drawBitmap(logo, null, new RectF(70, 70, 150, 150), null);

        Paint text = new Paint(Paint.ANTI_ALIAS_FLAG);
        text.setColor(Color.rgb(16, 32, 51));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(56);
        c.drawText("Granpa", 170, 125, text);

        text.setTextSize(52);
        c.drawText("Recommended Pump", 70, 235, text);

        text.setColor(Color.rgb(0, 83, 176));
        text.setTextSize(70);
        c.drawText(safe(r.model), 70, 330, text);

        int y = 395;
        drawChip(c, "⚡", PumpSelector.trim(r.hp) + " HP", 70, y, 210, 120);
        drawChip(c, "⚡", PumpSelector.trim(r.kw) + " kW", 300, y, 210, 120);
        drawChip(c, "~", phaseLabel(r.phase), 530, y, 230, 120);
        drawChip(c, "◉", compactType(r.category), 780, y, 230, 120);

        y = 550;
        p.setColor(Color.rgb(247, 251, 255));
        p.setStyle(Paint.Style.FILL);
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(207, 221, 236));
        c.drawRoundRect(new RectF(70, y, 1010, y + 70), 18, 18, p);
        text.setColor(Color.rgb(16, 32, 51));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        text.setTextSize(30);
        String req = hasEstimate
                ? "Suitable for " + PumpSelector.head(head) + " head  •  Estimated " + PumpSelector.lph(flow)
                : "Model details and complete performance curve";
        drawSingleLineFit(c, req, 115, y + 45, text, 860);

        y = 650;
        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(255, 248, 238));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(255, 132, 0));
        c.drawRoundRect(new RectF(70, y, 1010, y + 90), 18, 18, p);
        text.setColor(Color.rgb(16, 32, 51));
        text.setTextSize(33);
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText(hasEstimate ? "Estimated at " + PumpSelector.head(head) + ":" : "Flow range:", 125, y + 58, text);
        text.setColor(Color.rgb(232, 92, 0));
        text.setTextSize(48);
        text.setTextAlign(Paint.Align.RIGHT);
        String out = hasEstimate ? PumpSelector.lph(flow) : flowRange(r);
        c.drawText(out, 960, y + 60, text);
        text.setTextAlign(Paint.Align.LEFT);

        drawChart(c, r, hasEstimate, head, flow, new RectF(70, 790, 1010, 1320));

        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.rgb(247, 251, 255));
        c.drawRoundRect(new RectF(70, 1380, 1010, 1445), 18, 18, p);
        if (logo != null) c.drawBitmap(logo, null, new RectF(95, 1390, 145, 1440), null);
        text.setColor(Color.rgb(96, 112, 133));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.NORMAL));
        text.setTextSize(24);
        String left = "Generated by ";
        c.drawText(left, 165, 1423, text);
        float nextX = 165 + text.measureText(left);
        text.setColor(Color.rgb(0, 83, 176));
        text.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        c.drawText("Granpa Pump Selector", nextX, 1423, text);
        return bm;
    }

    public static File save(Activity a, Bitmap bm) throws Exception {
        File dir = new File(a.getCacheDir(), "share");
        if (!dir.exists()) dir.mkdirs();
        File file = new File(dir, "granpa_pump_share.png");
        FileOutputStream out = new FileOutputStream(file);
        bm.compress(Bitmap.CompressFormat.PNG, 100, out);
        out.flush();
        out.close();
        return file;
    }

    public static void shareImage(Activity a, PumpRecord r, boolean hasEstimate, double head, double flow, boolean whatsappOnly) {
        try {
            Bitmap bm = build(a, r, hasEstimate, head, flow);
            File file = save(a, bm);
            Uri uri = FileProvider.getUriForFile(a, a.getPackageName() + ".fileprovider", file);
            Intent i = new Intent(Intent.ACTION_SEND);
            i.setType("image/png");
            i.putExtra(Intent.EXTRA_STREAM, uri);
            i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            if (whatsappOnly) {
                i.setPackage("com.whatsapp");
                try { a.startActivity(i); return; }
                catch (Exception ignored) {
                    i.setPackage("com.whatsapp.w4b");
                    try { a.startActivity(i); return; }
                    catch (Exception ignored2) {}
                }
                Toast.makeText(a, "WhatsApp not found. Opening share menu.", Toast.LENGTH_SHORT).show();
                i.setPackage(null);
            }
            a.startActivity(Intent.createChooser(i, "Share pump image"));
        } catch (Exception e) {
            Toast.makeText(a, "Unable to create share image", Toast.LENGTH_LONG).show();
        }
    }

    static void drawChip(Canvas c, String icon, String label, int x, int y, int w, int h) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setColor(Color.WHITE);
        p.setStyle(Paint.Style.FILL);
        c.drawRoundRect(new RectF(x, y, x + w, y + h), 18, 18, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(207, 221, 236));
        c.drawRoundRect(new RectF(x, y, x + w, y + h), 18, 18, p);

        Paint t = new Paint(Paint.ANTI_ALIAS_FLAG);
        t.setColor(Color.rgb(0, 83, 176));
        t.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        t.setTextSize(34);
        t.setTextAlign(Paint.Align.CENTER);
        c.drawText(icon, x + w / 2f, y + 42, t);
        t.setColor(Color.rgb(16, 32, 51));
        t.setTextSize(label.contains("\n") ? 24 : 26);
        String[] lines = label.split("\n");
        float startY = lines.length == 1 ? y + 82 : y + 72;
        for (int i = 0; i < lines.length && i < 2; i++) c.drawText(lines[i], x + w / 2f, startY + i * 28, t);
    }

    static void drawChart(Canvas c, PumpRecord r, boolean hasEstimate, double head, double flow, RectF outer) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setStyle(Paint.Style.FILL);
        p.setColor(Color.WHITE);
        c.drawRoundRect(outer, 20, 20, p);
        p.setStyle(Paint.Style.STROKE);
        p.setStrokeWidth(2);
        p.setColor(Color.rgb(221, 229, 239));
        c.drawRoundRect(outer, 20, 20, p);

        Paint title = new Paint(Paint.ANTI_ALIAS_FLAG);
        title.setColor(Color.rgb(16, 32, 51));
        title.setTypeface(Typeface.create(Typeface.DEFAULT, Typeface.BOLD));
        title.setTextSize(30);
        c.drawText("Performance Curve", outer.left + 32, outer.top + 42, title);

        RectF plot = new RectF(outer.left + 95, outer.top + 82, outer.right - 35, outer.bottom - 160);
        ArrayList<double[]> realPts = new ArrayList<>();
        if (r.curve != null) {
            for (double[] q : r.curve) {
                if (q != null && q.length >= 2 && !Double.isNaN(q[0]) && !Double.isNaN(q[1])) realPts.add(new double[]{q[0], q[1]});
            }
        }
        Collections.sort(realPts, Comparator.comparingDouble(a -> a[1]));
        if (realPts.isEmpty()) return;

        double maxF = 0, maxH = 0;
        for (double[] q : realPts) {
            maxF = Math.max(maxF, q[1]);
            maxH = Math.max(maxH, q[0]);
        }
        if (hasEstimate) {
            maxF = Math.max(maxF, flow);
            maxH = Math.max(maxH, head);
        }
        if (maxF < 1) maxF = 1000;
        if (maxH < 1) maxH = 10;
        double axisMaxF = roundUp(maxF, niceFlowStep(maxF));
        double axisMaxH = roundUp(maxH * 1.08, 10);
        if (axisMaxH < 10) axisMaxH = 10;

        Paint grid = new Paint(Paint.ANTI_ALIAS_FLAG);
        grid.setColor(Color.rgb(225, 232, 241));
        grid.setStrokeWidth(1.5f);
        Paint text = new Paint(Paint.ANTI_ALIAS_FLAG);
        text.setColor(Color.rgb(16, 32, 51));
        text.setTextSize(22);
        text.setTextAlign(Paint.Align.CENTER);

        for (int i = 0; i <= 5; i++) {
            float gx = plot.left + i * plot.width() / 5f;
            c.drawLine(gx, plot.top, gx, plot.bottom, grid);
            c.drawText(String.format(Locale.US, "%,.0f", axisMaxF * i / 5), gx, plot.bottom + 34, text);
        }
        text.setTextAlign(Paint.Align.RIGHT);
        for (int i = 0; i <= 5; i++) {
            float gy = plot.bottom - i * plot.height() / 5f;
            c.drawLine(plot.left, gy, plot.right, gy, grid);
            c.drawText(String.format(Locale.US, "%.0f", axisMaxH * i / 5), plot.left - 14, gy + 8, text);
        }

        Paint axis = new Paint(Paint.ANTI_ALIAS_FLAG);
        axis.setColor(Color.rgb(96, 112, 133));
        axis.setStrokeWidth(2);
        c.drawLine(plot.left, plot.top, plot.left, plot.bottom, axis);
        c.drawLine(plot.left, plot.bottom, plot.right, plot.bottom, axis);

        text.setTextAlign(Paint.Align.CENTER);
        text.setTextSize(26);
        c.drawText("Flow Rate (LPH)", plot.centerX(), plot.bottom + 74, text);
        c.save();
        c.rotate(-90, outer.left + 42, plot.centerY());
        c.drawText("Head (m)", outer.left + 42, plot.centerY(), text);
        c.restore();

        ArrayList<double[]> displayPts = new ArrayList<>();
        displayPts.add(new double[]{maxH, 0});
        for (double[] q : realPts) displayPts.add(new double[]{q[0], q[1]});
        displayPts.add(new double[]{0, axisMaxF});

        Paint curvePaint = new Paint(Paint.ANTI_ALIAS_FLAG);
        curvePaint.setColor(Color.rgb(0, 96, 216));
        curvePaint.setStyle(Paint.Style.STROKE);
        curvePaint.setStrokeWidth(5);
        curvePaint.setStrokeCap(Paint.Cap.ROUND);
        curvePaint.setStrokeJoin(Paint.Join.ROUND);
        Path path = new Path();
        for (int i = 0; i < displayPts.size(); i++) {
            float cx = x(displayPts.get(i)[1], axisMaxF, plot);
            float cy = y(displayPts.get(i)[0], axisMaxH, plot);
            if (i == 0) path.moveTo(cx, cy);
            else {
                float px = x(displayPts.get(i - 1)[1], axisMaxF, plot);
                float py = y(displayPts.get(i - 1)[0], axisMaxH, plot);
                float mx = (px + cx) / 2f;
                path.cubicTo(mx, py, mx, cy, cx, cy);
            }
        }
        c.drawPath(path, curvePaint);

        if (hasEstimate) {
            float sx = x(flow, axisMaxF, plot);
            float sy = y(head, axisMaxH, plot);
            Paint dash = new Paint(Paint.ANTI_ALIAS_FLAG);
            dash.setColor(Color.rgb(255, 132, 0));
            dash.setStyle(Paint.Style.STROKE);
            dash.setStrokeWidth(2);
            dash.setPathEffect(new DashPathEffect(new float[]{10, 8}, 0));
            c.drawLine(plot.left, sy, sx, sy, dash);
            c.drawLine(sx, sy, sx, plot.bottom, dash);
            Paint dot = new Paint(Paint.ANTI_ALIAS_FLAG);
            dot.setColor(Color.rgb(255, 132, 0));
            c.drawCircle(sx, sy, 13, dot);
        }

        Paint legend = new Paint(Paint.ANTI_ALIAS_FLAG);
        legend.setTextSize(24);
        legend.setColor(Color.rgb(16, 32, 51));
        legend.setTextAlign(Paint.Align.LEFT);
        Paint blueLine = new Paint(Paint.ANTI_ALIAS_FLAG);
        blueLine.setColor(Color.rgb(0, 96, 216));
        blueLine.setStrokeWidth(5);
        blueLine.setStrokeCap(Paint.Cap.ROUND);
        float ly = outer.bottom - 38;
        c.drawLine(outer.left + 115, ly - 7, outer.left + 165, ly - 7, blueLine);
        c.drawText(r.model + " Performance Curve", outer.left + 180, ly, legend);
        Paint orange = new Paint(Paint.ANTI_ALIAS_FLAG);
        orange.setColor(Color.rgb(255, 132, 0));
        c.drawCircle(outer.left + 595, ly - 7, 10, orange);
        c.drawText("Selected Operating Point", outer.left + 615, ly, legend);
    }

    static void drawSingleLineFit(Canvas c, String s, float x, float y, Paint paint, float maxWidth) {
        float oldSize = paint.getTextSize();
        while (paint.measureText(s) > maxWidth && paint.getTextSize() > 22) {
            paint.setTextSize(paint.getTextSize() - 1);
        }
        c.drawText(s, x, y, paint);
        paint.setTextSize(oldSize);
    }

    static double niceFlowStep(double maxF) {
        if (maxF <= 1000) return 200;
        if (maxF <= 3000) return 500;
        if (maxF <= 10000) return 1000;
        if (maxF <= 30000) return 5000;
        return 10000;
    }

    static double roundUp(double value, double step) { return Math.ceil(value / step) * step; }
    static float x(double f, double axisMaxF, RectF r) { return (float) (r.left + (f / axisMaxF) * r.width()); }
    static float y(double h, double axisMaxH, RectF r) { return (float) (r.bottom - (h / axisMaxH) * r.height()); }
    static String safe(String s) { return s == null ? "" : s.trim(); }
    static String phaseLabel(String p) { p = safe(p).toUpperCase(Locale.US); if (p.contains("S")) return "Single Phase"; if (p.contains("T")) return "Three Phase"; return p.isEmpty() ? "Phase -" : p; }
    static String compactType(String category) {
        String c = safe(category).toLowerCase(Locale.US);
        if (c.contains("borewell")) return "Borewell\nSubmersible";
        if (c.contains("openwell")) return "Openwell\nSubmersible";
        if (c.contains("monoblock")) return "Monoblock";
        if (c.contains("centrifugal")) return "Centrifugal";
        return safe(category).replace(" - ", "\n");
    }
    static String flowRange(PumpRecord r) { return Double.isNaN(r.minFlowLPH) || Double.isNaN(r.maxFlowLPH) ? "-" : PumpSelector.lph(r.minFlowLPH).replace(" LPH", "") + "–" + PumpSelector.lph(r.maxFlowLPH); }
}
