name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: texmo_pump_selector_native_android

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: texmo-pump-selector-debug-apk
          path: texmo_pump_selector_native_android/app/build/outputs/apk/debug/*.apk
